school/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('teachers/', include('teachers.urls'))
]

students/urls.py
from django.urls import path
from . import views
app_name="students"
urlpatterns = [

    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('classes/', views.classes, name='classes'),
    path('contacts/', views.contacts, name='contacts')

]

teachers/urls.py
from django.urls import path
from . import views
app_name='teachers'

urlpatterns = [

    path('about/', views.about, name='about'),
    path('classes/', views.classes,name='classes'),
    path('contacts/', views.contacts, name='contacts')
]

students/models.py
from django.db import models

# Create your models here.

teachers/models.py
from django.db import models

# Create your models here.

students/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html', {'navbar':'index'})

def about(request):
    return render(request, 'about.html', {'navbar':'about'})

def classes(request):
    return render(request, 'classes.html', {'navbar': 'classes'})
def contacts(request):
    return render(request, 'contacts.html', {'navbar': 'contacts'})

teachers/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    context={'navbar=index'}
    return render(request, 'about.html',context)
def classes(request):
    return render(request, 'classes.html')
def contacts(request):
    return render(request,'contacts.html')

students/templates/about.html
{% extends 'index.html' %}
{% load static %}
{% block  body%}
	<p class="one">about page</p>
    <img src="{% static 'images/logo.png' %}" alt="">
{% endblock %}

students/templates/classes.html
{% extends 'index.html' %}
{% block body%}

{% endblock %}

students/templates/contacts.html
{% extends 'index.html' %}
{% block body%}

{% endblock %}

students/templates/index.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<p>index from students app</p>
<a class="{% if navbar == 'index' %} two {% endif %}" href="{% url 'students:index' %}">Home</a>
<a class="{% if navbar == 'about' %} two {% endif %}" href="{% url 'students:about' %}">about</a>
<a class="{% if navbar == 'contacts' %} two {% endif %}" href="{% url 'students:contacts' %}">contacts</a>
<a class="{% if navbar == 'classes' %} two {% endif %}" href="{% url 'students:classes' %}">classes</a>
<button class="btn bg-primary m-2">This is bootstrap</button>

{% block body %}
{% endblock %}


</body>
</html>